[project]
name = "linker"
version = "0.1.0"
description = "Aggregate information everywhere"
authors = [{ name = "Nikita Grigorenko" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest (>=8.4.2,<9.0.0)",
    "sqlalchemy (>=2.0.44,<3.0.0)",
    "psycopg2-binary (>=2.9.11,<3.0.0)",
    "alembic (>=1.17.1,<2.0.0)",
    "scrapy (>=2.13.3,<3.0.0)",
    "ipython (>=9.7.0,<10.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
