# Generated by Django 5.2.8 on 2025-11-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
    ]
