# Generated by Django 5.2.8 on 2025-11-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0002_auto_20251125_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='WebPageArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('html', models.TextField()),
                ('archived', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'web_page_archives',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(
                    blank=True, max_length=100, null=True)),
                ('article_authors', models.ManyToManyField(blank=True,
                 related_name='article_authors', to='crawler.article')),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='authored_articles', to='crawler.author'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='authored_books', to='crawler.author')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='book_authors',
            field=models.ManyToManyField(
                blank=True, related_name='book_authors', to='crawler.book'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='authored_videos', to='crawler.author')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='video_authors',
            field=models.ManyToManyField(
                blank=True, related_name='video_authors', to='crawler.video'),
        ),
    ]
