# Generated by Django 5.2.8 on 2025-11-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
